// <auto-generated />
using System;
using Courier.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Courier.Web.Migrations
{
    [DbContext(typeof(CourierContext))]
    [Migration("20231130151958_data")]
    partial class data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Courier.Web.Entities.Delivery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CourierId")
                        .HasColumnType("bigint");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeliveryStatus")
                        .HasColumnType("int");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("TimeDelivered")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Deliveries");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CourierId = 1L,
                            DeliveryAddress = "Some address",
                            DeliveryStatus = 0,
                            OrderId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CourierId = 2L,
                            DeliveryAddress = "Some address",
                            DeliveryStatus = 0,
                            OrderId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            CourierId = 3L,
                            DeliveryAddress = "Some address",
                            DeliveryStatus = 1,
                            OrderId = 3L,
                            TimeDelivered = new DateTime(2023, 11, 30, 16, 19, 58, 639, DateTimeKind.Local).AddTicks(9524)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
