// <auto-generated />
using System;
using Courier.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Courier.Web.Migrations
{
    [DbContext(typeof(CourierContext))]
    [Migration("20231228161606_latandlong")]
    partial class latandlong
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Courier.Web.Entities.Delivery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CourierId")
                        .HasColumnType("bigint");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeliveryStatus")
                        .HasColumnType("int");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("TimeClaimed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeDelivered")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Deliveries");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CourierId = 1L,
                            DeliveryAddress = "Janusevej 90, 2300 København S",
                            DeliveryStatus = 0,
                            OrderId = 1L,
                            TimeClaimed = new DateTime(2023, 12, 28, 17, 16, 6, 158, DateTimeKind.Local).AddTicks(4219)
                        },
                        new
                        {
                            Id = 2L,
                            CourierId = 2L,
                            DeliveryAddress = "Frederiksgade 9, 8000 Helsingør C",
                            DeliveryStatus = 0,
                            OrderId = 2L,
                            TimeClaimed = new DateTime(2023, 12, 28, 17, 16, 6, 158, DateTimeKind.Local).AddTicks(4275)
                        },
                        new
                        {
                            Id = 3L,
                            CourierId = 3L,
                            DeliveryAddress = "Julisvej 9, 2300 København S",
                            DeliveryStatus = 1,
                            OrderId = 3L,
                            TimeClaimed = new DateTime(2023, 12, 28, 17, 16, 6, 158, DateTimeKind.Local).AddTicks(4278),
                            TimeDelivered = new DateTime(2023, 12, 28, 17, 16, 6, 158, DateTimeKind.Local).AddTicks(4280)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
